First screen
JuliaSokolenko/IT-Studio pull request #1
Opened 2021-07-03 14:38 UTC by JuliaSokolenko

2021-07-07 07:51 UTC, anttibull requested changes

2021-07-07 07:51 UTC, anttibull commented on button.css
> +}
добавь здесь пжл пустую строку в конце файла (на 25 строке)

2021-07-07 07:51 UTC, anttibull commented on button.css
> +    font-family: Montserrat;
здесь к этому шрифту добавь еще sans-serif
```suggestion
    font-family: Montserrat, sans-serif;
```

2021-07-07 07:51 UTC, anttibull commented on button.css
> +    font-family: Montserrat;
еще рекомендую посмотреть css-переменные — https://developer.mozilla.org/ru/docs/Web/CSS/Using_CSS_custom_properties 

Считается хорошей практикой использовать переменные в местах, где значения повторяются, к примеру это могут быть шрифты, цвета ...

2021-07-07 07:51 UTC, anttibull commented on first-screen.css
> +}
добавь здесь пжл пустую строку в конце файла

2021-07-07 07:51 UTC, anttibull commented on first-screen__menu.css
> +}
добавь здесь пжл пустую строку в конце файла (на 25 строке)

2021-07-07 07:51 UTC, anttibull commented on index.html
>  </html>
добавь здесь пжл пустую строку в конце файла (на 25 строке)

2021-07-07 08:04 UTC, anttibull commented on first-screen__menu.css
> +.nav{
переименуй еще этот файл на `nav.less`

Названия файлов должны быть такими же как и названия блока

2021-07-07 19:18 UTC, stakansoljarki requested changes

2021-07-07 19:18 UTC, stakansoljarki commented on button.css
> +    font-style: normal;
можна не використовувати

2021-07-15 16:25 UTC, anttibull requested changes

2021-07-15 16:25 UTC, anttibull commented on index.html
> +            <header class="first-screen__header">
тебе здесь не хватает блоков-контейнеров, который будут ограничивать твой контент по ширине. Это обычно `div` с классом `container`. По макету у тебя ширина контейнера должны быть 1100px

Вот как должно быть:
<img width="1000" alt="Screenshot 2021-07-15 at 19 00 07" src="https://user-images.githubusercontent.com/32951804/125819802-c42c0451-6bb3-4b3f-afd2-b3314d1fe3c4.png">

Вот как сейчас: 
<img width="1787" alt="Screenshot 2021-07-15 at 19 08 16" src="https://user-images.githubusercontent.com/32951804/125820897-879d55c2-0db8-45be-a5f0-da5ec523cebb.png">

2021-07-15 16:25 UTC, anttibull commented on index.html
> +                <h1 class="title">Мы создаем легкие решения<br>
Использовать br в таком случаи для переноса строки считается плохой практикой

2021-07-15 16:25 UTC, anttibull commented on first-screen.css
> +.title{
Если это отельный компонент, то я бы вынес это в отдельный файл, тк они позже юзаться могут не только в first-screen

2021-07-15 16:25 UTC, anttibull commented on first-screen.css
> +.subtitle{
аналогично

2021-07-23 13:58 UTC, stakansoljarki requested changes

2021-07-23 13:58 UTC, stakansoljarki commented on first-screen.css
> +.title{
попередній раз писали за це

2021-07-23 13:58 UTC, stakansoljarki commented on first-screen.css
> +    margin-top: 219px;
тобі потрібно змістити вниз внутрішні елементи цього блоко, а не сам блок
для цого використовується падінг

2021-07-23 13:58 UTC, stakansoljarki commented on button.css
> +    background-color: #4985FF;
використовуй маленькі букви для значення кольору

2021-07-23 13:58 UTC, stakansoljarki commented on button.css
> +    padding: 13px 36px 15px 36px;
і скорочений варіант значення падінгів - 
```suggestion
    padding: 13px 36px 15px;
```

2021-07-23 13:58 UTC, stakansoljarki commented on button.css
> +    text-decoration: none;
цю властивість можна перенести в ресет цсс

2021-07-23 13:58 UTC, stakansoljarki commented on index.html
> +            <header class="first-screen__header">
```container``` не підійде, тому що ломається БЕМ
всередині цього блока повинні бути тільки його елементи, а тут всі елементи являються елементами ```fisrt-screen```
можна зробить ```first-screen__container```

2021-07-23 13:58 UTC, stakansoljarki commented on index.html
> +                <h1 class="title">Мы создаем легкие решения<br>
можна використати максимальну ширину і потім відцентрувати вміст ```first-screen__content```

2021-08-09 08:42 UTC, stakansoljarki commented on first-screen.css
> +    height: 100%;
для чого тобі тут висота 100%?
у нього не може бути 100% висоті, тому що поруч з цим блоком є ще один і вони знаходяться в одному контейнері
тепер цей блок виходить за межі батьківського контейнеру

2021-08-09 08:42 UTC, stakansoljarki commented on index.html
> +
повидаляй пусті рядки між тегами в цьому файлі

2021-08-09 08:42 UTC, stakansoljarki commented on nav.css
> +    margin-right: 20px;
для чого тобі марджин тут?

2021-08-09 16:09 UTC, JuliaSokolenko commented on first-screen.css
> +    height: 100%;
Ок, я приберу

2021-08-09 16:17 UTC, JuliaSokolenko commented on nav.css
> +    margin-right: 20px;
Щоб змістити меню трохи вліво. Але оскільки є контейнер, то марджин тут не потрібен. Приберу теж

2021-08-10 19:35 UTC, stakansoljarki commented on nav.css
> +    margin-right: 20px;
так, краще добавить 20px для контейнера, в якому знаходиться навігація - ```first-screen__container```, тому що це внутрішній відступ, але не в навігації, а в контейнера
цей відступ потрібен для того, щоб на екранах менше 1100px твоя навігація не була прижата до правого краю повністю, в майбутньому це буде потрібно для респонсіва.

2021-08-11 06:10 UTC, anttibull approved these changes

2021-08-11 10:15 UTC, JuliaSokolenko commented on first-screen.css
> +    height: 100%;
Бо поряд два блока в одному контейнері. При висоті 100% first-screen__content виходить за межі цього контейнеру

2021-08-11 11:23 UTC, JuliaSokolenko commented on nav.css
> +    margin-right: 20px;
Цей відступ потрібен тільки для навігації? Чи й для first-screen__content також?

2021-08-11 11:28 UTC, stakansoljarki commented on nav.css
> +    margin-right: 20px;
він потрібен тільки для ```first-screen__content```
і потрібен ```padding```, не ```margin```

2021-08-11 11:29 UTC, stakansoljarki commented on nav.css
> +    margin-right: 20px;
по суті це один фікс, так шо даю апрув

2021-08-11 11:29 UTC, stakansoljarki approved these changes

2021-08-11 11:48 UTC, merged