Responsive first-screen
JuliaSokolenko/IT-Studio pull request #12
Opened 2022-01-13 11:46 UTC by JuliaSokolenko

2022-01-18 17:47 UTC, anttibull requested changes

2022-01-18 17:47 UTC, anttibull commented on src/js/index.js
> +})
не пойму зачем это нужно

2022-01-18 17:47 UTC, anttibull commented on src/js/index.js
> +})
Оберни это в функции (аналогично, как сделаны `handleNavigation` и `handleHeaderFill` ) и вызывай это вместе с другими функциями ниже

2022-01-18 17:47 UTC, anttibull commented on src/pug/header.pug
> +
лишний отступ)

2022-01-18 18:08 UTC, JuliaSokolenko commented on src/js/index.js
> +})
щоб відстежувать клік і щоб бургер меню закривалось

2022-01-20 11:11 UTC, stakansoljarki approved these changes

2022-01-20 11:11 UTC, stakansoljarki commented on src/scss/header.scss
> +                &.header__burger-layers {
```suggestion
                &.header { 
                  &__burger-layers {
```

2022-01-22 13:04 UTC, anttibull requested changes

2022-01-22 13:04 UTC, anttibull commented on src/js/index.js
> +}
обсудили на звонке

2022-01-22 13:04 UTC, anttibull commented on src/js/index.js
> +}
эта функция сейчас не работает должным образом

2022-01-23 10:59 UTC, anttibull requested changes

2022-01-23 10:59 UTC, anttibull commented on src/js/index.js
>          if(!target.closest('.header__burger')) {
```suggestion
        if(target !== button) {
```

2022-01-23 10:59 UTC, anttibull commented on src/js/index.js
> +const handleToggleBurgerMenu = () => {
```suggestion
const burgerMenu = document.querySelector('.header__burger-layers')

const handleToggleBurgerMenu = () => {
```

2022-01-23 10:59 UTC, anttibull commented on src/js/index.js
>              nav.classList.remove('nav--visible')
мне кажется ты забыла убрать класс еще и  c `burgerMenu`

2022-01-23 12:03 UTC, JuliaSokolenko commented on src/js/index.js
>          if(!target.closest('.header__burger')) {
А чого так, як було, не можна?(

2022-01-23 12:12 UTC, JuliaSokolenko commented on src/js/index.js
>              nav.classList.remove('nav--visible')
Наступний же рядок в коді `burgerMenu.classList.remove('header__burger-layers--cross')`

2022-01-24 17:30 UTC, anttibull approved these changes

2022-01-24 17:39 UTC, merged