Parcel
JuliaSokolenko/IT-Studio pull request #3
Opened 2021-09-14 11:43 UTC by JuliaSokolenko

2021-09-16 17:44 UTC, anttibull requested changes

2021-09-16 17:44 UTC, anttibull commented on src/pug/services.pug
> +        a.services__button.button(href='#all services') Все услуги
давай сделаем это через интерполяцию 
```suggestion
- const title = 'Мы создаем мобильные приложения для крупных корпораций';
- const description = 'Lorem Ipsum - это текст-"рыба", часто используемый в печати и вэб-дизайне. Lorem Ipsum является стандартной "рыбой" для текстов на латинице с начала XVI века.';
- const buttonTitle = 'Все услуги';

- 
    const serviceData = [
        { 
            iconSrc: '../assets/images/project.svg', 
            altIcon: 'project',
            title: 'Создание сайтов', 
            description: 'Lorem Ipsum - это текст-"рыба", часто используе в печати и вэб-дизайне.'
        },
        { 
            iconSrc: '../assets/images/project.svg', 
            altIcon: 'project',
            title: 'Создание сайтов', 
            description: 'Lorem Ipsum - это текст-"рыба", часто используе в печати и вэб-дизайне.'
        },
        { 
            iconSrc: '../assets/images/project.svg', 
            altIcon: 'project',
            title: 'Создание сайтов', 
            description: 'Lorem Ipsum - это текст-"рыба", часто используе в печати и вэб-дизайне.'
        },
    ];

section.services
    .services__container
        .services__text-wrap
            h2.services__title.title=title
            p.services__text.text=description
        ul.services__content
            each item in serviceData
                li.services__item
                    img.services__icon(
                        src=item.iconSrc,
                        alt=item.description
                    )
                    .services__info
                        h3.services__heading.heading #{item.title}
                        p.services__description #{item.description}
        a.services__button.button(href='#all services') #{buttonTitle}
```

2021-09-16 17:44 UTC, anttibull commented on src/pug/services.pug
> +        a.services__button.button(href='#all services') Все услуги
давай сделаем это через интерполяцию 
```suggestion
- const title = 'Мы создаем мобильные приложения для крупных корпораций';
- const description = 'Lorem Ipsum - это текст-"рыба", часто используемый в печати и вэб-дизайне. Lorem Ipsum является стандартной "рыбой" для текстов на латинице с начала XVI века.';
- const buttonTitle = 'Все услуги';

- 
    const serviceData = [
        { 
            iconSrc: '../assets/images/project.svg', 
            altIcon: 'project',
            title: 'Создание сайтов', 
            description: 'Lorem Ipsum - это текст-"рыба", часто используе в печати и вэб-дизайне.'
        },
        { 
            iconSrc: '../assets/images/project.svg', 
            altIcon: 'project',
            title: 'Создание сайтов', 
            description: 'Lorem Ipsum - это текст-"рыба", часто используе в печати и вэб-дизайне.'
        },
        { 
            iconSrc: '../assets/images/project.svg', 
            altIcon: 'project',
            title: 'Создание сайтов', 
            description: 'Lorem Ipsum - это текст-"рыба", часто используе в печати и вэб-дизайне.'
        },
    ];

section.services
    .services__container
        .services__text-wrap
            h2.services__title.title=title
            p.services__text.text=description
        ul.services__content
            each item in serviceData
                li.services__item
                    img.services__icon(
                        src=item.iconSrc,
                        alt=item.description
                    )
                    .services__info
                        h3.services__heading.heading #{item.title}
                        p.services__description #{item.description}
        a.services__button.button(href='#all services') #{buttonTitle}
```

2021-09-16 17:44 UTC, anttibull commented on src/pug/first-screen.pug
> +                a.nav__link.nav__link--secondary(href='#main') Главная
```suggestion
                a.nav__link(href='#main') Главная
```

Давай сейчас избавимся тут от этого класса. Позже предлагаю сделать хедер фиксированным и напишем чутка js что бы этот класс накидывался на актуальную `nav__link` при скроле страницы

2021-09-16 17:44 UTC, anttibull commented on src/pug/first-screen.pug
> +                a.nav__link(href='#contacts') Контакты
И сделай хедер через интерполяцию с циклом (как в service)

2021-10-07 07:38 UTC, anttibull commented on .prettierrc
> +
No new line at and of file

2021-10-07 07:40 UTC, anttibull commented on src/js/index.js
> +);
👍👍👍

2021-10-07 07:45 UTC, anttibull commented on src/scss/header.scss
> +}
```suggestion
.header {
    position: fixed;
    top: 0;
    width: 100%;
    border-bottom: 1px solid #a1a1a1;
    &__container {
      width: 100%;
      max-width: 1100px;
      margin: 0 auto;
      padding: 0 20px;
  }
}
```

2021-10-07 12:03 UTC, stakansoljarki commented on src/scss/first-screen.scss
> +$color: #fff;
Є така штука, як область видимості ( рекомендую прочитать про це трішки детальніше, інфи небагато буде ). Вона буває локальною і глобальною. В твоєму варіанті змінна ```$color``` являється глобальною і може використовуватись в будь-якому файлі в проекті, але твій варіант трішки неправильний, тому що ця змінна створенна у файлі ```first-screen```. Логічно було би, щоб змінна, яка створюється в якомусь конкретному файлі, використовувалась тільки в цьому ж файлі і ніде більше. Для цього її потрібно створити нижче, там де ти вказуєш стилі для ```.first-screen```. Це означатиме, що змінна може використовуватись тільки в межах блоку ```first-screen``` та його дочірніх елементів.
Разом з тим, колір ```#fff``` зустрічається у тебе не тільки для ```first-screen```, але є й у кнопки, тому логічно, що ця змінна повинна бути глобальною, а не локальною. Для глобальних змінних створюються окремі файли: ```variables.scss```, ```colors.scss```, ```mixins.scss```
Variables - тут, зачасту, створюються змінні для розмірів екранів/ z-index/ шрифтів і тд.
Colors - для кольорів
Mixins - для міксінів
Рекомендую почитать про це. Це не складно і інфи там небагато, але будеш розуміти що і як, в подальшому тобі будуть потрібні ці файли і вони будуть розширюватись.
Тому пропоную тобі зараз створити новий файл - ```color.scss```, куди добавимо першу змінну для кольору - ```$white: #fff;``` і використати її в цьому файлі і також для кольору кнопки

2021-10-07 12:06 UTC, stakansoljarki commented on src/scss/first-screen.scss
> +    }
```suggestion
   
```
видаляємо ці стилі, тому що це зайва обгортка і відповідно потрібно буде відцентрувати ```first-screen__container```, думаю це можна зробити за допомогою флексів, їх потрібно вказати для ```first-screen```, оскільки в ньому є 2 блоки - хедер і контейнер, а враховуючи що хедер фіксований, то флексами ти спозиціонуєш саме ```first-screen__container``` по центру екрану

2021-10-07 12:12 UTC, stakansoljarki commented on src/scss/header.scss
> +    position: fixed;
якщо ти хочеш зробити його фіксованим, то потрібно добавити якийсь колір бекгарунду для хедера, тому що зараз при скролі відбувається ось це
<img width="1321" alt="Screen Shot 2021-10-07 at 15 10 35" src="https://user-images.githubusercontent.com/57605002/136381407-e0df1d03-ee7e-4c73-9a80-1af66a467bba.png">
ось так буде краще, як на мене
колір можеш вибрати інший)
<img width="1324" alt="Screen Shot 2021-10-07 at 15 11 27" src="https://user-images.githubusercontent.com/57605002/136381569-e80a73ff-b281-494e-943a-41c1f931fa98.png">

2021-10-07 12:13 UTC, stakansoljarki commented on src/scss/index.scss
> +@import 'reset.scss';
файли ```variables```, ```mixins```, ```colors``` підключаються після ```reset```, тому як створиш ```colors.scss```, його потрібно буде підключити в цьому місці

2021-11-04 11:53 UTC, anttibull commented on src/js/index.js
> +})
добавь пустую строку в конце файла

2021-11-05 09:20 UTC, anttibull approved these changes

2021-11-05 09:38 UTC, merged