About-us branch
JuliaSokolenko/IT-Studio pull request #5
Opened 2021-11-08 18:21 UTC by JuliaSokolenko

2021-11-17 18:16 UTC, stakansoljarki approved these changes

2021-11-18 08:21 UTC, anttibull requested changes

2021-11-18 08:21 UTC, anttibull commented on src/pug/about-us.pug
> +                a.about-us__link(href='#about company') #{ linkName }
```suggestion
                a.about-us__link(href="тут нужно через интерполяию") #{ linkName }
```

2021-11-18 08:21 UTC, anttibull commented on src/pug/about-us.pug
> +            img.about-us__image(src='../assets/images/work.png', alt='work')
```suggestion
            img.about-us__image(src='аналогично', alt='аналогично')
```

2021-11-18 08:21 UTC, anttibull commented on src/pug/about-us.pug
> +    ];
Давай сделаем что бы все наши данные были в одном обьекте:
```suggestion
-
    const data = {
        title: "Высокие стандарты разработки", 
        description: 'Lorem Ipsum - это текст-"рыба", часто используемый в печати и вэб-дизайне. Lorem Ipsum является стандартной "рыбой" для текстов на латинице с начала XVI века. стандартной "рыбой" для текстов на латинице с начала XVI века.',
        link: '#about company',
        linkTitle: "Подробнее о компании",
        imageSrc: '../assets/images/work.png', 
        imageAlt: 'work',
        projects: [
            {
                iconSrc: '../assets/images/web-programming.svg',
                altIcon: 'web-programming',
                number: '125',
                caption: 'Our projects'
            },
            {
                iconSrc: '../assets/images/web-programming.svg',
                altIcon: 'web-programming',
                number: '125',
                caption: 'Our projects'
            },
            {
                iconSrc: '../assets/images/web-programming.svg',
                altIcon: 'web-programming',
                number: '125',
                caption: 'Our projects'
            },
            {
                iconSrc: '../assets/images/web-programming.svg',
                altIcon: 'web-programming',
                number: '125',
                caption: 'Our projects'
            },
            {
                iconSrc: '../assets/images/web-programming.svg',
                altIcon: 'web-programming',
                number: '125',
                caption: 'Our projects'
            },
        ], 
    };
```

2021-11-18 08:21 UTC, anttibull commented on src/pug/about-us.pug
> +                    p.about-us__caption.text #{ item.caption }
Когда ты закинешь все данные в один обьект, здесь получится в итоге 
```suggestion
section#services.about-us 
    .about-us__container 
        article.about-us__description
            .about-us__text-wrap 
                h2.about-us__title.title= data.title
                p.about-us__text.text= data.description
                a.about-us__link(href=data.link) #{ data.linkTitle }
            img.about-us__image(src=data.imageSrc, alt=data.imageAlt)
        ul.about-us__projects 
            each item in data.projects 
                li.about-us__item 
                    .about-us__info
                        img.about-us__icon(src=item.iconSrc, alt=item.altIcon)
                        p.about-us__number #{ item.number }
                    p.about-us__caption.text #{ item.caption }
```

2021-11-18 08:22 UTC, anttibull commented
и переименуй пжл назавание pr, это не ветка)

2021-11-19 17:24 UTC, anttibull approved these changes

2021-11-19 18:12 UTC, merged