All-services component
JuliaSokolenko/IT-Studio pull request #6
Opened 2021-11-23 17:34 UTC by JuliaSokolenko

2021-11-26 09:32 UTC, anttibull requested changes

2021-11-26 09:32 UTC, anttibull commented on src/pug/all-services.pug
> +                number: '01.',
Давай добавим какое то различие для этих блоков
```suggestion
                number: '02.',
```

2021-11-26 09:32 UTC, anttibull commented on src/pug/all-services.pug
> +                number: '01.',
```suggestion
                number: '03.',
```

2021-11-26 09:32 UTC, anttibull commented on src/pug/all-services.pug
> +                            #[span.all-services__number #{ item.number }]
может просто: 
```suggestion
                            span.all-services__number #{ item.number }
```
?

2021-11-26 13:37 UTC, stakansoljarki requested changes

2021-11-26 13:37 UTC, stakansoljarki commented on src/scss/all-services.scss
> +        max-height: 490px;
получається так, що контейнер для контенту по висоті менший за сам контент, так не може бути
подумай, яким способом пожна вирішить цей момент

2021-11-26 13:37 UTC, stakansoljarki commented on src/scss/all-services.scss
> +            linear-gradient(90deg, #504dc2 20.44%, #5f12d0 80.91%);
```suggestion
        background-image: linear-gradient(90deg, #504dc2 20.44%, #5f12d0 80.91%);
```

не зовсім розумію, для чого цей колір потрібен.
якщо він дійсно треба, тоді не змінюй нічого)

2021-11-26 13:37 UTC, stakansoljarki commented on src/scss/all-services.scss
> +        }
```suggestion
        &:not(:last-child) {
            margin-right: 30px;
        }
```

2021-11-26 13:37 UTC, stakansoljarki commented on src/scss/all-services.scss
> +        }
рекомендую прочитать статейку про псевдокласи, можна робить цікаві речі простішим способом і не добавляючи зайвий код

2021-11-26 13:37 UTC, stakansoljarki commented on src/scss/all-services.scss
> +        font-family: $font;
якось провтикав цей момент
я би назвав змінну для шрифта по-іншому, як варіант ```$font-main```
ну і потрібно буде замінить назву в усіх місцях, де використовувалась змінна

2021-12-03 17:40 UTC, stakansoljarki approved these changes

2021-12-03 17:40 UTC, stakansoljarki commented on src/scss/header.scss
> +    z-index: 1000;
1000?)
мені здається, що 1 буде достатньо) може 5, подивись чи буде якийсь контент відображатись поверх хедера

2021-12-03 17:50 UTC, JuliaSokolenko commented on src/scss/header.scss
> +    z-index: 1000;
То я просто забула прибрати)

2021-12-03 19:58 UTC, anttibull approved these changes
Поправь z-index и можешь мержить

2021-12-03 20:16 UTC, merged